name: SIMAPA

on:
    pull_request:
        branches:
            - pipeline

    push:
        branches:
            - pipeline
    
jobs:
    test:
        runs-on: ubuntu-latest
        container:
            image: mysql:8
            env:
                mysql_ALLOW_EMPTY_PASSWORD: 'yes'
                MYSQL_ROOT_PASSWORD: ""
                MYSQL_DATABASE: app
                MYSQL_USER: root
                MYSQL_PASSWORD: ""
            ports:
                - 3306:3306
            options: >-
                --health-cmd="mysqladmin ping --silent"
                --health-interval=10s
                --health-timeout=5s
                --health-retries=3
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '22'
            
            - name: Install dependencies
              run: npm install
            
            - name: Copy Environment Variables
              run: cp .env.example .env

            - name: Generate Application Key
              run: node ace generate:key

            - name: Run Migrations
              run: node ace migration:run --force

            - name: Run Tests
              run: node ace test --force-exit